import os
import argparse

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # video is rendered to a file, no display is needed
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from config import get_configuration

# Simulation area boundaries in meters.
# These must match northern_bound / southern_bound / eastern_bound / western_bound
# in the scenario's default_config.properties file.
AREA_BOUNDS = {'x_min': 0, 'x_max': 1000, 'y_min': 0, 'y_max': 1000}


def _read_location_log(file_path, id_column):
    """
    Reads a *_USER_LOCATIONS.log or *_UAV_LOCATIONS.log file (generated by SimLogger)
    into a DataFrame. File format: '#auto generated file!' header followed by rows of
    time;id;x_pos;y_pos
    """
    data = pd.read_csv(file_path, sep=';', header=None, skiprows=1,
                        names=['time', id_column, 'x', 'y'])
    # ONAT: round so that timestamps sampled via repeated event rescheduling (UAVs)
    # line up with timestamps computed via direct multiplication (users/SAR).
    data['time'] = data['time'].round(2)
    return data


def generate_user_location_heatmap_video(scenario=None, num_devices=None, iteration=1,
                                          grid_size=40, fps=5, output_path=None):
    """
    Generates a video showing how the spatial distribution (heat map) of normal
    users changes throughout the simulation, with SAR team members overlaid as
    distinctly colored markers, based on the per-user position log.
    """
    config = get_configuration()
    folder_path = config['folder_path']
    num_sar_members = config['num_sar_members']

    if scenario is None:
        scenario = config['scenario_types'][0]
    if num_devices is None:
        num_devices = config['max_devices']

    file_name = f'SIMRESULT_DEFAULT_SCENARIO_WORST_FIT_{scenario}_{num_devices}DEVICES_USER_LOCATIONS.log'
    file_path = os.path.join(folder_path, f'ite{iteration}', file_name)

    print(f"Reading user location log -> {file_path}")
    try:
        data = _read_location_log(file_path, id_column='device_id')
    except FileNotFoundError:
        print(f"Warning: File not found -> {file_path}")
        return

    time_steps = np.sort(data['time'].unique())
    if len(time_steps) == 0:
        print("No data found in the log file, aborting.")
        return

    # ONAT: SAR members are appended after the normal-user devices (see MainApp),
    # so ids >= num_devices belong to the SAR population.
    normal_data = data[data['device_id'] < num_devices]
    sar_data = data[data['device_id'] >= num_devices]

    uav_file_name = f'SIMRESULT_DEFAULT_SCENARIO_WORST_FIT_{scenario}_{num_devices}DEVICES_UAV_LOCATIONS.log'
    uav_file_path = os.path.join(folder_path, f'ite{iteration}', uav_file_name)
    try:
        uav_data = _read_location_log(uav_file_path, id_column='uav_id')
        print(f"Reading UAV location log -> {uav_file_path}")
    except FileNotFoundError:
        print(f"Warning: UAV location file not found -> {uav_file_path} (video will not show UAVs)")
        uav_data = pd.DataFrame(columns=['time', 'uav_id', 'x', 'y'])

    x_edges = np.linspace(AREA_BOUNDS['x_min'], AREA_BOUNDS['x_max'], grid_size + 1)
    y_edges = np.linspace(AREA_BOUNDS['y_min'], AREA_BOUNDS['y_max'], grid_size + 1)

    # Pre-compute the 2D histogram (heat map) for every time step so that the
    # color scale can be normalized consistently across the whole video.
    heatmaps = []
    sar_positions = []
    uav_positions = []
    for t in time_steps:
        frame_data = normal_data[normal_data['time'] == t]
        hist, _, _ = np.histogram2d(frame_data['x'], frame_data['y'], bins=[x_edges, y_edges])
        heatmaps.append(hist.T)

        sar_frame_data = sar_data[sar_data['time'] == t]
        sar_positions.append(sar_frame_data[['x', 'y']].to_numpy())

        uav_frame_data = uav_data[uav_data['time'] == t]
        uav_positions.append(uav_frame_data[['x', 'y']].to_numpy())

    vmax = max(h.max() for h in heatmaps)

    fig, ax = plt.subplots(figsize=(7, 6))
    plt.rcParams.update({'font.family': 'Times New Roman', 'font.size': 11})

    im = ax.imshow(heatmaps[0], origin='lower', cmap='YlOrRd', vmin=0, vmax=vmax,
                    extent=[AREA_BOUNDS['x_min'], AREA_BOUNDS['x_max'],
                            AREA_BOUNDS['y_min'], AREA_BOUNDS['y_max']])
    # ONAT: SAR team members plotted in a distinct color on top of the normal-user heat map.
    sar_scatter = ax.scatter(sar_positions[0][:, 0], sar_positions[0][:, 1],
                              c='cyan', edgecolors='black', linewidths=0.5, s=30,
                              label=f'SAR members ({num_sar_members})', zorder=3)
    # ONAT: UAVs (edge servers) plotted with their own distinct marker/color.
    uav_scatter = ax.scatter(uav_positions[0][:, 0], uav_positions[0][:, 1],
                              c='lime', marker='^', edgecolors='black', linewidths=0.5, s=80,
                              label='UAVs', zorder=4)
    ax.set_xlabel('X Position (m)')
    ax.set_ylabel('Y Position (m)')
    title = ax.set_title(f'Client Density Heat Map (t = {time_steps[0]:.0f}s)')
    ax.legend(loc='upper right')
    fig.colorbar(im, ax=ax, label='# of Clients')
    fig.tight_layout()

    def update(frame_index):
        im.set_data(heatmaps[frame_index])
        sar_scatter.set_offsets(sar_positions[frame_index])
        uav_scatter.set_offsets(uav_positions[frame_index])
        title.set_text(f'Client Density Heat Map (t = {time_steps[frame_index]:.0f}s)')
        return im, sar_scatter, uav_scatter, title

    ani = animation.FuncAnimation(fig, update, frames=len(time_steps), blit=False)

    if output_path is None:
        os.makedirs(folder_path, exist_ok=True)
        output_path = os.path.join(folder_path, f'user_location_heatmap_{scenario}_{num_devices}DEVICES.mp4')

    ani.save(output_path, writer=animation.FFMpegWriter(fps=fps))
    print(f"Video saved to {output_path}")
    plt.close(fig)


def _parse_args():
    config = get_configuration()
    parser = argparse.ArgumentParser(
        description='Generate a video of the client density heat map over the course of the simulation.')
    parser.add_argument('--scenario', default=None, choices=config['scenario_types'],
                         help='UAV mobility policy to visualize. If omitted, a video is generated for every policy.')
    parser.add_argument('--num-devices', type=int, default=config['max_devices'],
                         help='Number of mobile devices of the simulation to visualize.')
    parser.add_argument('--iteration', type=int, default=1, help='Simulation iteration (ite<N>) to visualize.')
    parser.add_argument('--grid-size', type=int, default=40, help='Number of heat map bins per axis.')
    parser.add_argument('--fps', type=int, default=5, help='Frames per second of the generated video.')
    parser.add_argument('--output', default=None, help='Output video file path (only valid with a single --scenario).')
    return parser.parse_args()


if __name__ == '__main__':
    print("--- Generating: User Location Heat Map Video ---")
    args = _parse_args()
    config = get_configuration()

    # ONAT: render every UAV mobility policy unless the user asked for a specific one.
    scenarios_to_render = [args.scenario] if args.scenario else config['scenario_types']
    for scenario in scenarios_to_render:
        generate_user_location_heatmap_video(scenario=scenario, num_devices=args.num_devices,
                                              iteration=args.iteration, grid_size=args.grid_size,
                                              fps=args.fps,
                                              output_path=args.output if len(scenarios_to_render) == 1 else None)
