import os
import argparse

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # video is rendered to a file, no display is needed
import matplotlib.pyplot as plt
import matplotlib.animation as animation

from config import get_configuration

# Simulation area boundaries in meters.
# These must match northern_bound / southern_bound / eastern_bound / western_bound
# in the scenario's default_config.properties file.
AREA_BOUNDS = {'x_min': 0, 'x_max': 1000, 'y_min': 0, 'y_max': 1000}


def _read_user_locations(file_path):
    """
    Reads a *_USER_LOCATIONS.log file (generated by SimLogger) into a DataFrame.
    File format: '#auto generated file!' header followed by rows of
    time;device_id;x_pos;y_pos
    """
    return pd.read_csv(file_path, sep=';', header=None, skiprows=1,
                        names=['time', 'device_id', 'x', 'y'])


def generate_user_location_heatmap_video(scenario=None, num_devices=None, iteration=1,
                                          grid_size=40, fps=5, output_path=None):
    """
    Generates a video showing how the spatial distribution (heat map) of mobile
    users changes throughout the simulation, based on the per-user position log.
    """
    config = get_configuration()
    folder_path = config['folder_path']

    if scenario is None:
        scenario = config['scenario_types'][0]
    if num_devices is None:
        num_devices = config['max_devices']

    file_name = f'SIMRESULT_DEFAULT_SCENARIO_WORST_FIT_{scenario}_{num_devices}DEVICES_USER_LOCATIONS.log'
    file_path = os.path.join(folder_path, f'ite{iteration}', file_name)

    print(f"Reading user location log -> {file_path}")
    try:
        data = _read_user_locations(file_path)
    except FileNotFoundError:
        print(f"Warning: File not found -> {file_path}")
        return

    time_steps = np.sort(data['time'].unique())
    if len(time_steps) == 0:
        print("No data found in the log file, aborting.")
        return

    x_edges = np.linspace(AREA_BOUNDS['x_min'], AREA_BOUNDS['x_max'], grid_size + 1)
    y_edges = np.linspace(AREA_BOUNDS['y_min'], AREA_BOUNDS['y_max'], grid_size + 1)

    # Pre-compute the 2D histogram (heat map) for every time step so that the
    # color scale can be normalized consistently across the whole video.
    heatmaps = []
    for t in time_steps:
        frame_data = data[data['time'] == t]
        hist, _, _ = np.histogram2d(frame_data['x'], frame_data['y'], bins=[x_edges, y_edges])
        heatmaps.append(hist.T)

    vmax = max(h.max() for h in heatmaps)

    fig, ax = plt.subplots(figsize=(7, 6))
    plt.rcParams.update({'font.family': 'Times New Roman', 'font.size': 11})

    im = ax.imshow(heatmaps[0], origin='lower', cmap='YlOrRd', vmin=0, vmax=vmax,
                    extent=[AREA_BOUNDS['x_min'], AREA_BOUNDS['x_max'],
                            AREA_BOUNDS['y_min'], AREA_BOUNDS['y_max']])
    ax.set_xlabel('X Position (m)')
    ax.set_ylabel('Y Position (m)')
    title = ax.set_title(f'Client Density Heat Map (t = {time_steps[0]:.0f}s)')
    fig.colorbar(im, ax=ax, label='# of Clients')
    fig.tight_layout()

    def update(frame_index):
        im.set_data(heatmaps[frame_index])
        title.set_text(f'Client Density Heat Map (t = {time_steps[frame_index]:.0f}s)')
        return im, title

    ani = animation.FuncAnimation(fig, update, frames=len(time_steps), blit=False)

    if output_path is None:
        os.makedirs(folder_path, exist_ok=True)
        output_path = os.path.join(folder_path, f'user_location_heatmap_{scenario}_{num_devices}DEVICES.mp4')

    ani.save(output_path, writer=animation.FFMpegWriter(fps=fps))
    print(f"Video saved to {output_path}")
    plt.close(fig)


def _parse_args():
    config = get_configuration()
    parser = argparse.ArgumentParser(
        description='Generate a video of the client density heat map over the course of the simulation.')
    parser.add_argument('--scenario', default=config['scenario_types'][0], choices=config['scenario_types'],
                         help='Mobility scenario to visualize.')
    parser.add_argument('--num-devices', type=int, default=config['max_devices'],
                         help='Number of mobile devices of the simulation to visualize.')
    parser.add_argument('--iteration', type=int, default=1, help='Simulation iteration (ite<N>) to visualize.')
    parser.add_argument('--grid-size', type=int, default=40, help='Number of heat map bins per axis.')
    parser.add_argument('--fps', type=int, default=5, help='Frames per second of the generated video.')
    parser.add_argument('--output', default=None, help='Output video file path.')
    return parser.parse_args()


if __name__ == '__main__':
    print("--- Generating: User Location Heat Map Video ---")
    args = _parse_args()
    generate_user_location_heatmap_video(scenario=args.scenario, num_devices=args.num_devices,
                                          iteration=args.iteration, grid_size=args.grid_size,
                                          fps=args.fps, output_path=args.output)
