# ONAT: Used to store tutorial names for both explanation and execution purposes
tutorial8=LocalComparison
tutorial9=VORONOIComparison
tutorial10=CentralizedComparison
tutorial11=VORONOIvsKMEANSComparison
tutorial12=KMEANSComparison